### ISSUE TITLE
License

### ISSUE THREAD

**Issue by DaanVanYperen** [locknic/Sudokil#1]
Heya! Found your game scanning for artemis-odb games, your project might be interesting reference for other artemis-odb users. What kind of license is the source under?

**Comment by locknic** [comment]
@DaanVanYperen Hi Daan, thank you for considering Sudokil as a reference! I must admit I've not thought much about licenses before this conversation, I was hoping you might be able to recommend one. Essentially I would like to allow people to use my code as reference for help and use similar code in their work, but of course I do not want people to be able to copy the entire game to build upon. 

Aside from that, if you have the time to have a quick look at how I am using artemis-odb, I would appreciate some feedback/suggestions since you are so familiar with it!

**Comment by DaanVanYperen** [comment]
Think I turned my github alerts off by accident, didn't notice your response @locknic! 

Take a look at http://choosealicense.com/, it explains all the licenses.  What you describe sits closest to exclusive copyright I think, combined with github's terms of service still allows users to view (and learn) without having a right to reproduce or use.

I'll definitely take a gander, doubt I'll have much input, i'm used to making overly rushed Jam games to be honest. ;) No time to polish!

**Comment by locknic** [comment]
@DaanVanYperen I forgot to tag you when I first made the comment, so I added it in! Is there a template for exclusive copyright that I can use for github? Cheers.

**Comment by DaanVanYperen** [comment]
Figure i'd get a message regardless, since I put the ticket in.

Anway, surprisingly couldn't find a license template for exclusive copyright, though it's what you have by default. You could consider adding a readme.md that explains the code is copyrighted if you like!

**Comment by locknic** [comment]
@DaanVanYperen I will add that to my todo list! Cheers for all the help Daan.
